# Generated by Django 4.2.7 on 2023-11-06 00:39

import UserAccountHub.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_DateTime', models.DateTimeField(auto_now=True)),
                ('DateTime_UTC', UserAccountHub.models.DateTimeUTCField(auto_now=True, null=True)),
                ('Update_DateTime_UTC', UserAccountHub.models.DateTimeUTCField(auto_now=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=180, unique=True, verbose_name='email')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=60)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'In Active'), (2, 'Suspended')], default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('date_of_Birth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_DateTime', models.DateTimeField(auto_now=True)),
                ('dateTime_UTC', UserAccountHub.models.DateTimeUTCField(auto_now=True, null=True)),
                ('update_DateTime_UTC', UserAccountHub.models.DateTimeUTCField(auto_now=True)),
                ('accountNumber', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='USD', max_length=4)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'In Active'), (2, 'Suspended')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccountHub.user')),
            ],
        ),
    ]
