# Generated by Django 4.2.7 on 2023-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JOD', 'Jordanian Dinar')], default='USD', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'In Active'), (2, 'Suspended'), (3, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'In Active'), (2, 'Suspended'), (3, 'Deleted')], default=0),
        ),
    ]
