# Generated by Django 4.2.7 on 2023-11-18 21:15

import UserAccountHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountHub', '0002_alter_account_accountnumber_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'IN_ACTIVE'), (2, 'SUSPENDED'), (3, 'DELETED')], default=UserAccountHub.models.AccountStatus['ACTIVE']),
        ),
    ]
